#!/bin/bash

mkdir blastdb
export BLASTDB=blastdb
cd blastdb
wget ftp://ftp.ncbi.nlm.nih.gov/blast/db/16SMicrobial.tar.gz && tar xzvf 16SMicrobial.tar.gz && rm 16SMicrobial.tar.gz
wget ftp://ftp.ncbi.nlm.nih.gov/blast/db/swissprot.tar.gz && tar xzvf swissprot.tar.gz && rm swissprot.tar.gz
wget ftp://ftp.ncbi.nlm.nih.gov/blast/db/taxdb.tar.gz && tar xzvf taxdb.tar.gz && rm taxdb.tar.gz

mkdir blast
cd blast
wget https://s3-us-west-2.amazonaws.com/veri-analizi/test.fa 
wget https://s3-us-west-2.amazonaws.com/veri-analizi/garfield.fa 
wget https://s3-us-west-2.amazonaws.com/veri-analizi/human_swissprot.fa
wget https://s3-us-west-2.amazonaws.com/veri-analizi/ecoli_swissprot.fa
wget https://s3-us-west-2.amazonaws.com/veri-analizi/Ecoli-cds.fa
wget https://s3-us-west-2.amazonaws.com/veri-analizi/human_ensembl_transcripts.fa.gz
wget https://s3-us-west-2.amazonaws.com/veri-analizi/human_ensembl_proteins.fa.gz
wget https://s3-us-west-2.amazonaws.com/veri-analizi/all_human_viruses.fa
wget https://s3-us-west-2.amazonaws.com/veri-analizi/human_ensembl_transcripts_50.fa
