#!/bin/bash

jupyter labextension install @jupyterlab/toc

mkdir blastdb
cd blastdb
# wget ftp://ftp.ncbi.nlm.nih.gov/blast/db/16SMicrobial.tar.gz 
# wget ftp://ftp.ncbi.nlm.nih.gov/blast/db/swissprot.tar.gz
# wget ftp://ftp.ncbi.nlm.nih.gov/blast/db/taxdb.tar.gz

# due to ftp access errors during binder build, I had to mirror db files at S3
# thus S3 contents should be updated from time to time..
wget -q https://s3-us-west-2.amazonaws.com/veri-analizi/16SMicrobial.tar.gz  
wget -q https://s3-us-west-2.amazonaws.com/veri-analizi/swissprot.tar.gz
wget -q https://s3-us-west-2.amazonaws.com/veri-analizi/taxdb.tar.gz 

tar xzvf 16SMicrobial.tar.gz
rm 16SMicrobial.tar.gz
tar xzvf swissprot.tar.gz 
rm swissprot.tar.gz
tar xzvf taxdb.tar.gz
rm taxdb.tar.gz
cd 
wget -q https://s3-us-west-2.amazonaws.com/veri-analizi/test.fa 
wget -q https://s3-us-west-2.amazonaws.com/veri-analizi/garfield.fa 
wget -q https://s3-us-west-2.amazonaws.com/veri-analizi/human_swissprot.fa
wget -q https://s3-us-west-2.amazonaws.com/veri-analizi/ecoli_swissprot.fa
wget -q https://s3-us-west-2.amazonaws.com/veri-analizi/Ecoli-cds.fa
wget -q https://s3-us-west-2.amazonaws.com/veri-analizi/human_ensembl_transcripts.fa.gz
wget -q https://s3-us-west-2.amazonaws.com/veri-analizi/human_ensembl_proteins.fa.gz
wget -q https://s3-us-west-2.amazonaws.com/veri-analizi/all_human_viruses.fa
wget -q https://s3-us-west-2.amazonaws.com/veri-analizi/human_ensembl_transcripts_50.fa

# needed to use indexes downloaded from NCBI
# this didn't work: export BLASTDB=/home/jovyan/blastdb/
echo 'export BLASTDB="$HOME/blastdb/"' >> ~/.bashrc
